# Generated by Django 2.1.2 on 2019-01-04 21:19

from django.db import migrations, models
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20)),
                ('slug', models.SlugField(max_length=60)),
                ('mobile_1', models.CharField(max_length=12)),
                ('mobile_2', models.CharField(max_length=12)),
                ('mobile_3', models.CharField(max_length=12)),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
