# Generated by Django 2.1.2 on 2019-01-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mobile_1',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mobile_2',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mobile_3',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
